firebolt-db/dbt-firebolt

- dbt/adapters/firebolt/connections.py
fixes: #16 
drop the dbt-generated query_comment
the following query yields more immediately scannable/readable results
```SQL
SELECT START_TIME, DURATION, STATUS, QUERY_TEXT, ERROR_MESSAGE FROM catalog.query_history WHERE STATUS != 'STARTED_EXECUTION' ORDER BY START_TIME DESC LIMIT 50;
```
> drop the prefixed, dbt-generated metadata comment from SQL statements submitted to firebolt

- .github/pull_request_template.md
- CHANGELOG.md
this adds a PR template so that when opening a PR, developers are reminded to document their work and follow agreed-upon practices. I used [dbt-core's template](https://raw.githubusercontent.com/dbt-labs/dbt-core/main/.github/pull_request_template.md) as a reference, I'd love feedback on what we need/want here.
sidebar: @kevinmarr we need to get a CLA in place if we want to accept PRs from the community.
> add a PR template

- dbt/adapters/firebolt/__init__.py
Resolves problems with adapter firebolt not being found after update from 0.21.7 to 0.21.8.
> fix: Fixed missing adapter firebolt error

- .fossa.yml
- .github/workflows/security-scan.yml
- CHANGELOG.md
- sonar-project.properties
Resolves # FIR-10119
Adding security scan action to automatically spot any security hotspots via Sonar Cloud and Fossa.
> ci: Adding security scan

- .github/workflows/jaffle_shop.yml
- .github/workflows/jaffle_shop/profiles.yml
- .github/workflows/jaffle_shop/run_test_workflow.sh
Created an action for running jaffle shop testing.
> test: create jaffle_shop test action

- CHANGELOG.md
- dbt/adapters/firebolt/__init__.py
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/dbt_external_tables/create_external_table.sql
- dbt/include/firebolt/macros/dbt_external_tables/get_external_build_plan.sql
Previously, external table models with missing or misspelled `regex` or `data_type` fields caused indecipherable errors. Those errors are now clear. In addition, drop/create on external tables only occurs if variable is set: `dbt run-operation stage_external_sources  --vars "ext_full_refresh: true"`. Otherwise, table is skipped.
[dbt seeds doesn't truncate tables before running](https://packboard.atlassian.net/browse/FIR-10985)
> fix: External table models with missing fields now produce an error

- dev-requirements.txt
- setup.cfg
> fix: Moved all dev-requirements into setup.cfg.

- .github/pull_request_template.md
- CHANGELOG.md
- dbt/adapters/firebolt/impl.py
- dbt/adapters/firebolt/relation.py
- dbt/include/firebolt/macros/adapters.sql
- dbt/include/firebolt/macros/dbt_external_tables/create_external_table.sql
- dbt/include/firebolt/macros/dbt_external_tables/get_external_build_plan.sql
- dbt/include/firebolt/macros/materializations/seed.sql
- dbt/include/firebolt/macros/materializations/table.sql
- dbt/include/firebolt/macros/materializations/test.sql
- dbt/include/firebolt/macros/materializations/view.sql
- tests/integration/firebolt.dbtspec
Insures that all SQL commands in debug and log output have appropriate space before and after for ease of reading. Also some comment and style cleanup.
> style: Better log and debug output

- CHANGELOG.md
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/adapters.sql
Updated logic in FireboltIndexConfig.parse() in impl.py to deal with situations where key columns have only a single value. Index names are now formatted properly.
> fix: Correctly format index names

- CHANGELOG.md
- dbt/adapters/firebolt/__init__.py
- setup.cfg
- setup.py
Resolves FIR-13208
Moved the base requirement to dbt v1.1. This is in preparation for moving to the new testing suite that dbt has provided as of dbt v1.1.
> build: require dbt1.1

- CHANGELOG.md
- dbt/adapters/firebolt/__init__.py
- setup.cfg
Resolves https://packboard.atlassian.net/browse/FIR-15597
> feat: pass better error messages when API times out

- CHANGELOG.md
- dbt/include/firebolt/macros/catalog.sql
- tests/conftest.py
- tests/functional/adapter/test_basic.py
Catalog error was due to dbt tests assigning unique schema name to each run. We do not have schemas in Firebolt so when tests filtered results based on unique schema they got no data and failed down the line.
This extracts `table_schema` from `information_schema`, which is always set to `public`. Also `table_catalog` contains database name.
This change allows 3 more tests to pass.
> test: Fixing catalog error

- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/adapters/apply_grants.sql
- dbt/include/firebolt/macros/materializations/models/incremental/incremental.sql
- dbt/include/firebolt/macros/materializations/table.sql
- dbt/include/firebolt/macros/materializations/view.sql
- tests/functional/adapter/test_grants.py
Ref #71 
Adding placeholders for Grant tests. Since Firebolt does not support table-level permissions we can't really test the above.
We're throwing an error when explicitly trying to set grants so there's no unexpected functionality for the user.
> test: Adding grant tests

- .changes/unreleased/Changed-20230213-140852.yaml
- .github/workflows/code-check.yml
- .github/workflows/pull_request.yml
- .pre-commit-config.yaml
- dbt/include/firebolt/macros/materializations/models/incremental/incremental.sql
- setup.cfg
FIR-17190
Views are supposed to be more performant when used for the purpose of resolving columns. This also avoids creating a lot of "garbage" by repeatedly creating/deleting tables.
Users can override the behaviour by setting `tmp_relation_type`.
Also, setting compatibility to dbt-core<1.4 since that version contains breaking changes for us.
> perf: Using views for temp ops in incremental

- tests/functional/adapter/test_basic.py
Allowing tests to pass with old and new types in Firebolt.
> test: Fix type check between old and new types

- .changes/unreleased/Added-20230417-154152.yaml
- .github/workflows/jaffle_shop/profiles.yml
- dbt/include/firebolt/macros/adapters.sql
- tests/conftest.py
Enable multithreading in DBT. Adding multithreading to tests.
> feat: Allow multiple threads

- .changes/unreleased/Fixed-20230426-162250.yaml
- dbt/adapters/firebolt/column.py
- tests/unit/test_firebolt_adapter.py
Fixing an error when get_columns_in_relation macro would return types incompatible with Firebolt database. Adding tests to spot those errors in the future.
> fix: column type resolution

- .changes/unreleased/Fixed-20230504-095842.yaml
- .changes/unreleased/Fixed-20230504-110400.yaml
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/materializations/models/incremental/on_schema_change.sql
This helps debug an issue when schema changes occur. 
Also, fixing a deprecated error message parsing.
> fix: Better error message on schema mismatch

- .github/workflows/integration-tests.yml
using cache in the ci in order to re-run only the failed tests in order to save some time
>  ci: Caching failed tests for re-run

- .changes/unreleased/Added-20240117-110352.yaml
- .github/workflows/integration-tests-v1.yml
- .github/workflows/integration-tests-v2.yml
- README.md
- dbt/adapters/firebolt/connections.py
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/adapters.sql
- setup.cfg
- tests/conftest.py
- tests/functional/adapter/hooks/data/seed_model.sql
- tests/functional/adapter/hooks/data/seed_run.sql
- tests/functional/adapter/hooks/test_model_hooks.py
- tests/functional/adapter/test_column_types.py
- tests/functional/adapter/test_constraints.py
- tests/functional/adapter/test_query_comment.py
- tests/functional/adapter/test_simple_copy.py
- tests/functional/adapter/utils/test_utils.py
- tests/unit/test_firebolt_adapter.py
Resolves #103 
Adding new tests and constraints support to be compatible with dbt 1.5
Setting threads to 1 in order to avoid race conditions when multiple tests use the same table name. Once we have user schema support we can re enable it in order to speed up the testing.
Bumping Python version from 3.7 to 3.9, since there are some issues with inheritance resolution in pytest - overrides are not taken into account and base class fixtures and tests are run therefore failing the whole test suite.
> feat: constraints support and new tests

- .github/workflows/integration-tests-v1.yml
- setup.cfg
- tests/conftest.py
FIR-29705
Preventing accidental secret output.
Changing staging/dev secrets logic since the old one didn't handle special characters correctly and now we have those with the new credentials. In any case, dev will be retired soon.
> test: prevent secret output

- .changes/unreleased/Deprecated-20240126-113251.yaml
- .github/workflows/integration-tests-v1.yml
- .github/workflows/integration-tests-v2.yml
- .github/workflows/integration-tests.yml
- .github/workflows/jaffle-shop-v1.yml
- .github/workflows/jaffle-shop-v2.yml
- .github/workflows/jaffle_shop.yml
FIR-29774
Dev environment is retired, removing it.
> ci: Remove retired dev environment

- .changes/unreleased/Removed-20240126-115014.yaml
- .github/workflows/jaffle-shop-v1.yml
- .github/workflows/jaffle-shop-v2.yml
- setup.cfg
Removing 3.7 support as described in DBT 1.6 [guidelines](https://github.com/dbt-labs/dbt-core/discussions/7958).
> build: Remove Python 3.7 support

- .changes/unreleased/Fixed-20240304-112033.yaml
- dbt/include/firebolt/macros/adapters.sql
- tests/functional/adapter/test_basic.py
Avoid trimming whitespace after ( and before ) in CTAS.
We had issues when a model would contain a `-- comment` on the last line. With whitespace trimming it would place the whole model query inside `()` brackets, but the closing bracket would be inside a comment and therefore break the SQL.
e.g.
```
SELECT * FROM x -- this is a comment
```
compiles to
```
CREATE TABLE b AS
(SELECT * FROM x -- this is a comment)
```
This change fixes it by making sure there's always a newline after ( and before ).
> fix: Whitespace trim to allow comments in CTAS

- tests/functional/adapter/utils/test_utils.py
Firebolt syntax no longer supports `SELECT 'they\'re' as X` so this test is no longer relevant. This is similar to Postgres dialect, which has a switch that supports this legacy syntax.
In dbt-postgres this test is disabled as well.
> test: Skip backslash test

- .changes/unreleased/Changed-20240719-120150.yaml
- setup.cfg
dbt-core 1.8 contains breaking changes to our connector so we need to limit the max version to 1.7.*
> build: limit dbt-core to 1.8

- .github/workflows/code-check.yml
- .github/workflows/jaffle_shop/run_test_workflow.sh
- .github/workflows/nightly.yml
- setup.cfg
Using Jaffle Shop as running the full test suite that runs for over an hour is not feasible. This gives us a good overview if the main operations supported in DBT are still working on all of those Python versions and OSs.
> ci: Add nightly tests

- .changes/unreleased/Fixed-20240726-101135.yaml
- dbt/include/firebolt/macros/dbt_external_tables/create_external_table.sql
Whitespace was being truncated in this sql resulting in malformed query when compression is added.
> fix: Whitespace in external table compression

- .changes/unreleased/Fixed-20240828-120547.yaml
- tests/functional/adapter/test_store_test_failures.py
These tests rely on columns being nullable by default. We'll have to skip them for FB 1.0.
> test: Skip incompatible tests

- .changes/unreleased/Added-20240830-134618.yaml
- dbt/adapters/firebolt/connections.py
- dbt/adapters/firebolt/impl.py
- dbt/adapters/firebolt/relation.py
- setup.cfg
- tests/conftest.py
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_empty.py
- tests/functional/adapter/test_override.py
- tests/functional/adapter/test_query_comment.py
- tests/functional/adapter/unit_testing/test_unit_testing.py
- tests/functional/adapter/utils/test_utils.py
- tests/unit/test_firebolt_adapter.py
- tests/unit/test_firebolt_conversions.py
Resolves #124 
DBT 1.8 support with refactors required and new tests. Some imports have changed as well as interfaces.
We no longer need to pin the dbt-core version,  but need to make sure dbt-adapters module is included.
> feat(FIR-35169): dbt 1.8 support

- setup.cfg
Features like engine autostart are not available in the versions before.
> build: Set lower limit of the sdk to 1.5.0

- .changes/unreleased/Added-20240902-150119.yaml
- dbt/adapters/firebolt/connections.py
host parameter is used in some of the connectors instead of api_endpoint. We should support it as a part of the standard set of dbt connection parameters. Adding alias for this.
> feat(FIR-36122): Support host parameter as an alias

- .changes/unreleased/Fixed-20240904-150720.yaml
- .github/workflows/jaffle_shop/run_test_workflow.sh
- dbt/include/firebolt/macros/materializations/models/incremental/strategies.sql
insert_overwrite stategy used old synatx for detecting partitions. Updating the syntax not to use tuples (unsupported in Firebolt for now) and making sure the resulting columns are quoted.
Adding a test that checks that rerun worked.
> fix(FIR-36373): Incremental partition drop

- .pre-commit-config.yaml
- setup.cfg
Add classifiers to setup.cfg denoting support for Python 3.8 - 3.12. 
Also fixing pre-commit that would otherwise erase the changes.
> chore(FIR-34713): Add missing classifiers to setup.cfg

- .changes/unreleased/Changed-20240909-160913.yaml
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/utils/test_data_types.py
- tests/functional/adapter/utils/test_utils.py
Some of the skipped tests can now be enabled as the syntax to run them is now supported. Added ticket numbers to others.
> test(FIR-35179): re-enable some of the fixed tests

- .changes/unreleased/Fixed-20240910-171459.yaml
- .github/workflows/jaffle_shop/sources_external_tables_copy.yml
- dbt/include/firebolt/macros/dbt_external_tables/create_external_table.sql
Some arguments had incorrect nullability check. This led to broken SQL when nothing was specified for those arguments.
> fix(FIR-36503): Remove incorrect syntax in COPY logic

- .changes/unreleased/Fixed-20240912-171349.yaml
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/relations/table/create.sql
- tests/unit/test_index.py
Our index creation logic would break if columns constituting this index had spaces. Adding more advanced logic on index name creation as well as ability to override index name in config.
Also adding a failsafe if index is too long for Firebolt to handle - use the hash instead of failing.
> fix(FIR-12466): Allow indexes on columns with spaces

- .changes/unreleased/Added-20240912-162707.yaml
- README.md
- dbt/include/firebolt/macros/materializations/snapshot_merge.sql
- dbt/include/firebolt/macros/relations/table/create.sql
- tests/functional/adapter/test_basic.py
This change allows us to use DBT's Snapshot feature. We've been previously blocked by two things: `MERGE` query and `CREATE OR REPLACE TABLE`. Former was rewritten for the snapshotting purpose with INSERT and UPDATE queries. The  latter was achieved the same way as in [table materialisation](https://github.com/firebolt-db/dbt-firebolt/blob/674e35627b6e762a262cf1d067bf9149b1e6794a/dbt/include/firebolt/macros/materializations/table.sql#L25) (which snapshot does not go through).
> feat(FIR-10764): Snapshot support

- .changes/unreleased/Added-20240918-180154.yaml
- .github/workflows/jaffle_shop/sources_external_tables_copy.yml
- dbt/include/firebolt/macros/dbt_external_tables/create_external_table.sql
Adding WHERE clause to copy from.
> feat(FIR-36505): add where clause to copy from

- .changes/unreleased/Changed-20250115-095239.yaml
- dbt/adapters/firebolt/connections.py
- dbt/adapters/firebolt/impl.py
- dbt/include/firebolt/macros/adapters.sql
- tests/unit/test_index.py
Aggregation index SQL no longer requires key columns to be present as a part of it. Reflecting this change in dbt compiler.
> feat(FIR-42592): allow agg index without key columns

- .changes/unreleased/Changed-20250115-162017.yaml
- dbt/adapters/firebolt/connections.py
- setup.cfg
This makes sure we won't run into issues with outdated sdk version now that we're using ExtendedType.
> chore(FIR-42592): Update sdk dependency

- .changes/unreleased/Fixed-20250529-103401.yaml
- .github/workflows/code-check.yml
- setup.cfg
When installing dbt-firebolt with dbt-core 1.9 and up some of the files are not installed in the correct directory. This leads to dbt run failing with 
```
18:02:37  Encountered an error:
Runtime Error
Failed to read package: Runtime Error
No dbt_project.yml found at expected path /dbt/dbt-1.9-latest/lib/python3.11/site-packages/dbt/include/firebolt/dbt_project.yml
Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
```
Adding a fix that ensures the files are always included explicitly.
> fix(FIR-46528): dbt_project.yml not found

- .changes/unreleased/Fixed-20250603-163645.yaml
- .github/workflows/jaffle-shop-v1.yml
- .github/workflows/jaffle-shop-v2.yml
- setup.cfg
Previous fix was not including macros that were in subdirectories.
> fix: Include all macros from dbt adapter

- .changes/unreleased/Fixed-20250801-104442.yaml
- tests/conftest.py
- tests/functional/adapter/incremental/test_incremental.py
Fixes 1.0 tests since by default columns are not nullable but we're writing a null value.
> test(NoTicket): fix FB 1.0 tests
