firebolt-db/dbt-firebolt

README.md, dbt/adapters/firebolt/connections.py
Edited and restructured general information hierarchy as follows:
* dbt-firebolt
* Installation
* Setup
* Connecting to Firebolt
* Description of Firebolt Profile Fields
* Troubleshooting Connections
* Setup Recommendations
* quote_columns
* Supporting Concurrent Development
* Feature Support
* Using dbt-firebolt
* Model Configuration for Fact Tables
* Fact Table Configurations
* Example of a Fact Table With an Aggregating Index (Config Block Syntax)
* Model Configuration for Dimension Tables
* Dimension Table Configurations
* Example of a Dimension Table With a Join Index (Config Block Syntax)
* How Aggregating Indexes and Join Indexes Are Named
* Managing Ingestion via External Tables
* Installation of External Tables Package
* Using External Tables
* dbt_project.yml Syntax For an …
=> Polishing README; change names of engine and account profile params

README.md
Remove information that's now on the dbt docs site.
=> Remove duplicate information from README.md

MANIFEST.in, setup.cfg
Fixed package config in setup.cfg
=> fix: Setuptools config

.github/workflows/python-release-org.yml
=> ci: Create release action

.github/workflows/integration-tests.yml, test/integration/firebolt.dbtspec
Added integration test github action. Excluded tests that are currently failing, only two left: `empty` and `data_test`
=> ci: Setup testing

CONTRIBUTING.MD, README.md
Resolves # FIR-12448
Making sure we have contribution guidelines in all of our repos.
=> docs(FIR-12448): Create CONTRIBUTING.MD

.github/pull_request_template.md, CHANGELOG.md, dbt/adapters/firebolt/__init__.py, dbt/include/firebolt/macros/adapters.sql, dbt/include/firebolt/macros/materializations/models/incremental/incremental.sql
Resolves https://packboard.atlassian.net/browse/FIR-12464
Documenting adapters.sql as part of a general clean-up.
=> docs: Added docstrings to adapters.sql and cleaned up a variable name or two.

CHANGELOG.md, dbt/adapters/firebolt/connections.py, setup.cfg
Resolves https://packboard.atlassian.net/browse/FIR-12462
Finalized the response from the cursor.
=> feat: Better responses from cursor

.pre-commit-config.yaml
=> ci: Upgrade black version

CHANGELOG.md, dbt/adapters/firebolt/__init__.py, dbt/adapters/firebolt/column.py, dbt/adapters/firebolt/impl.py
=> fix: return 'text' for firebolt string columns

dbt/include/firebolt/macros/adapters.sql, dbt/include/firebolt/macros/catalog.sql, tests/functional/adapter/test_basic.py
Part of the #71 
Adding doc tests, fixing catalog generation to have correct information.
Fixed incorrect schema output.
=> test: Basic doc tests

.legitignore, dbt/adapters/firebolt/__init__.py, dbt/adapters/firebolt/connections.py, tests/unit/test_firebolt_adapter.py
Ref #71 
Implementing retry logic that's part of dbt-core 1.2. https://github.com/dbt-labs/dbt-core/pull/5432
=> feat: Retry connection on error

CHANGELOG.md
=> build: Changelog

.github/workflows/python-release-org.yml
=> ci: Fix release action

.changes/unreleased/Added-20230406-120454.yaml, .changes/unreleased/Fixed-20230405-173809.yaml, .changes/unreleased/Fixed-20230406-120358.yaml, .github/workflows/jaffle_shop.yml, .github/workflows/jaffle_shop/run_test_workflow.sh, dbt/adapters/firebolt/connections.py, dbt/include/firebolt/macros/adapters/apply_grants.sql
Fixing grant error by doing noop (return true) when copying over grants. All other macros are not called anywhere apart from overloaded macros so are safe to error out when used (because that means they're used incorrectly).
Also adding a flag to jaffle shop test to error on first command. Otherwise it was succeeding despite errors.
This exposed another issue with the query_comment attribute.
=> fix: dbt seed grant error

.changes/unreleased/Added-20230418-172018.yaml, dbt/include/firebolt/macros/adapters.sql, dbt/include/firebolt/macros/materializations/models/incremental/incremental.sql, dbt/include/firebolt/macros/materializations/models/incremental/merge.sql, dbt/include/firebolt/macros/materializations/models/incremental/strategies.sql, tests/functional/adapter/incremental/test_incremental.py
Allow delete+insert incremental strategy that does incremental data modification in two steps: deletes existing records and inserts existing and new ones without duplicates.
https://github.com/firebolt-db/dbt-firebolt/actions/runs/4734651782
https://github.com/firebolt-db/dbt-firebolt/actions/runs/4734653451
=> feat: Delete+insert incremental strategy

.github/workflows/integration-tests.yml, setup.cfg
Adding a way to visualise tests via the Allure action. Similar to analogous change in Python SDK.
Sample report: https://docs.firebolt.io/dbt-firebolt/6d47eecdb8efaabe0525b4936a34b24e6a7d5212_integration/64/#
N/A, internal change
=> ci: Add allure test reporting

.github/workflows/integration-tests-v1.yml, .github/workflows/integration-tests.yml, .github/workflows/python-release-org.yml
fixing CI to use centralised secrets
=> ci: Use org secrets

.changes/unreleased/Changed-20240801-164605.yaml, .changes/unreleased/Fixed-20240801-164536.yaml, dbt/include/firebolt/macros/adapters.sql, dbt/include/firebolt/macros/catalog.sql, tests/conftest.py, tests/functional/adapter/shared.py, tests/functional/adapter/test_basic.py, tests/functional/adapter/utils/test_utils.py
Fixing some of the tests that were broken by 2.0 release. Keeping it backwards-compatible.
[Success](https://github.com/firebolt-db/dbt-firebolt/actions/runs/10199871024)!
=> test: Fix config in conftest and other tests

.github/workflows/integration-tests-v1.yml
Fix integration tests. A change that was missed in the previous PR.
=> ci: Fix python installation in v1 integration tests

tests/functional/adapter/unit_testing/test_unit_testing.py
Fixing incompatibility between FB 1.0 and 2.0
=> test: Fix 1.0 test with quoting

dbt/adapters/firebolt/connections.py
There's no such thing anymore in similar adapters and tests are passing so this is an easy remove.
=> refactor(FIR-28918): Remove driver attribute

dbt/adapters/firebolt/impl.py, tests/unit/test_firebolt_adapter.py
Adding more tests to verify edge cases.
=> test(FIR-12467): improve unit test coverage
